-- MySQL Script generated by MySQL Workbench
-- 09/20/15 06:19:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema imt5401_mobile
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `imt5401_mobile` ;

-- -----------------------------------------------------
-- Schema imt5401_mobile
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `imt5401_mobile` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `imt5401_mobile` ;

-- -----------------------------------------------------
-- Table `imt5401_mobile`.`tblTeacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imt5401_mobile`.`tblTeacher` ;

CREATE TABLE IF NOT EXISTS `imt5401_mobile`.`tblTeacher` (
  `teacherID` INT NULL AUTO_INCREMENT COMMENT '',
  `firstName` LONGTEXT NOT NULL COMMENT '',
  `lastName` LONGTEXT NOT NULL COMMENT '',
  `gcmRegistrationID` LONGTEXT NOT NULL COMMENT '',
  PRIMARY KEY (`teacherID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imt5401_mobile`.`tblFloor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imt5401_mobile`.`tblFloor` ;

CREATE TABLE IF NOT EXISTS `imt5401_mobile`.`tblFloor` (
  `floorID` INT NULL AUTO_INCREMENT COMMENT '',
  `floorName` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`floorID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imt5401_mobile`.`tblBuilding`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imt5401_mobile`.`tblBuilding` ;

CREATE TABLE IF NOT EXISTS `imt5401_mobile`.`tblBuilding` (
  `buildingID` INT NULL AUTO_INCREMENT COMMENT '',
  `buildingName` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`buildingID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imt5401_mobile`.`tblRoom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imt5401_mobile`.`tblRoom` ;

CREATE TABLE IF NOT EXISTS `imt5401_mobile`.`tblRoom` (
  `roomID` INT NULL AUTO_INCREMENT COMMENT '',
  `roomName` VARCHAR(45) NOT NULL COMMENT '',
  `fk_tblFloor` INT NOT NULL COMMENT '',
  `fk_tblBuilding` INT NOT NULL COMMENT '',
  PRIMARY KEY (`roomID`)  COMMENT '',
  CONSTRAINT `fk_tblFloor`
    FOREIGN KEY (`fk_tblFloor`)
    REFERENCES `imt5401_mobile`.`tblFloor` (`floorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblBuilding`
    FOREIGN KEY (`fk_tblBuilding`)
    REFERENCES `imt5401_mobile`.`tblBuilding` (`buildingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tblRoom_tblFloor_idx` ON `imt5401_mobile`.`tblRoom` (`fk_tblFloor` ASC)  COMMENT '';

CREATE INDEX `fk_tblRoom_tblBuilding1_idx` ON `imt5401_mobile`.`tblRoom` (`fk_tblBuilding` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `imt5401_mobile`.`tblWebAdmin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imt5401_mobile`.`tblWebAdmin` ;

CREATE TABLE IF NOT EXISTS `imt5401_mobile`.`tblWebAdmin` (
  `adminID` INT NULL AUTO_INCREMENT COMMENT '',
  `adminName` VARCHAR(255) NOT NULL COMMENT '',
  `adminEmail` VARCHAR(255) NOT NULL COMMENT '',
  `adminPwd` LONGTEXT NOT NULL COMMENT '',
  PRIMARY KEY (`adminID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imt5401_mobile`.`tblRoomCorner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imt5401_mobile`.`tblRoomCorner` ;

CREATE TABLE IF NOT EXISTS `imt5401_mobile`.`tblRoomCorner` (
  `roomCornerID` INT NULL AUTO_INCREMENT COMMENT '',
  `cornerName` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`roomCornerID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imt5401_mobile`.`tblWifiNetworks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imt5401_mobile`.`tblWifiNetworks` ;

CREATE TABLE IF NOT EXISTS `imt5401_mobile`.`tblWifiNetworks` (
  `wifiID` INT NULL AUTO_INCREMENT COMMENT '',
  `wifiName` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`wifiID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imt5401_mobile`.`tblAccessPoints`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imt5401_mobile`.`tblAccessPoints` ;

CREATE TABLE IF NOT EXISTS `imt5401_mobile`.`tblAccessPoints` (
  `accessPointID` INT NULL AUTO_INCREMENT COMMENT '',
  `SSID` LONGTEXT NOT NULL COMMENT '',
  `MAC` LONGTEXT NOT NULL COMMENT '',
  `fk_tblRoom` INT NOT NULL COMMENT '',
  `fk_tblRoomCorner` INT NOT NULL COMMENT '',
  `fk_tblWifiNetworks` INT NOT NULL COMMENT '',
  PRIMARY KEY (`accessPointID`)  COMMENT '',
  CONSTRAINT `fk_tblRoom`
    FOREIGN KEY (`fk_tblRoom`)
    REFERENCES `imt5401_mobile`.`tblRoom` (`roomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblRoomCorner`
    FOREIGN KEY (`fk_tblRoomCorner`)
    REFERENCES `imt5401_mobile`.`tblRoomCorner` (`roomCornerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblWifiNetworks`
    FOREIGN KEY (`fk_tblWifiNetworks`)
    REFERENCES `imt5401_mobile`.`tblWifiNetworks` (`wifiID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tblAccessPoints_tblRoom1_idx` ON `imt5401_mobile`.`tblAccessPoints` (`fk_tblRoom` ASC)  COMMENT '';

CREATE INDEX `fk_tblAccessPoints_tblRoomCorner1_idx` ON `imt5401_mobile`.`tblAccessPoints` (`fk_tblRoomCorner` ASC)  COMMENT '';

CREATE INDEX `fk_tblAccessPoints_tblWifiNetworks1_idx` ON `imt5401_mobile`.`tblAccessPoints` (`fk_tblWifiNetworks` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `imt5401_mobile`.`tblStudent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imt5401_mobile`.`tblStudent` ;

CREATE TABLE IF NOT EXISTS `imt5401_mobile`.`tblStudent` (
  `studentID` VARCHAR(100) NOT NULL COMMENT '',
  `studentName` LONGTEXT NOT NULL COMMENT '',
  `gcmRegistrationID` LONGTEXT NOT NULL COMMENT '',
  PRIMARY KEY (`studentID`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
